//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace heliomaster_wpf.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    public sealed partial class MountSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static MountSettings defaultInstance = ((MountSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new MountSettings())));
        
        public static MountSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MountID {
            get {
                return ((string)(this["MountID"]));
            }
            set {
                this["MountID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n                    <Telescope>\r\n                    </Telescope>\r\n            " +
            "    ")]
        public global::heliomaster_wpf.Telescope Telescope {
            get {
                return ((global::heliomaster_wpf.Telescope)(this["Telescope"]));
            }
            set {
                this["Telescope"] = value;
            }
        }
    }
}
