//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace heliomaster.Properties {


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    public sealed partial class PowerSettings : global::System.Configuration.ApplicationSettingsBase {

        private static PowerSettings defaultInstance = ((PowerSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PowerSettings())));

        public static PowerSettings Default {
            get {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Netio")]
        public global::heliomaster.PowerTypes PowerType {
            get {
                return ((global::heliomaster.PowerTypes)(this["PowerType"]));
            }
            set {
                this["PowerType"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dome")]
        public string MountName {
            get {
                return ((string)(this["MountName"]));
            }
            set {
                this["MountName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mount")]
        public string DomeName {
            get {
                return ((string)(this["DomeName"]));
            }
            set {
                this["DomeName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<Power xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"                     " +
            "   xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\"> </Power>")]
        public global::heliomaster.Netio.Power Netio {
            get {
                return ((global::heliomaster.Netio.Power)(this["Netio"]));
            }
            set {
                this["Netio"] = value;
            }
        }
    }
}
