//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace heliomaster_wpf.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("heliomaster_wpf.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At home.
        /// </summary>
        public static string athome {
            get {
                return ResourceManager.GetString("athome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parked.
        /// </summary>
        public static string atpark {
            get {
                return ResourceManager.GetString("atpark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auto.
        /// </summary>
        public static string auto {
            get {
                return ResourceManager.GetString("auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capture.
        /// </summary>
        public static string capture {
            get {
                return ResourceManager.GetString("capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string close {
            get {
                return ResourceManager.GetString("close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dome.
        /// </summary>
        public static string dome {
            get {
                return ResourceManager.GetString("dome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to duration.
        /// </summary>
        public static string duration {
            get {
                return ResourceManager.GetString("duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to east.
        /// </summary>
        public static string east {
            get {
                return ResourceManager.GetString("east", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end at.
        /// </summary>
        public static string endat {
            get {
                return ResourceManager.GetString("endat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exp (ms).
        /// </summary>
        public static string exposure {
            get {
                return ResourceManager.GetString("exposure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gain.
        /// </summary>
        public static string gain {
            get {
                return ResourceManager.GetString("gain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquisition.
        /// </summary>
        public static string headerAcquisition {
            get {
                return ResourceManager.GetString("headerAcquisition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus.
        /// </summary>
        public static string headerFocus {
            get {
                return ResourceManager.GetString("headerFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to interval.
        /// </summary>
        public static string headerInterval {
            get {
                return ResourceManager.GetString("headerInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop condition.
        /// </summary>
        public static string headerStopCondition {
            get {
                return ResourceManager.GetString("headerStopCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string notavailable {
            get {
                return ResourceManager.GetString("notavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Not chosen yet].
        /// </summary>
        public static string notchosen {
            get {
                return ResourceManager.GetString("notchosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not running.
        /// </summary>
        public static string notrunning {
            get {
                return ResourceManager.GetString("notrunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # shots.
        /// </summary>
        public static string nshots {
            get {
                return ResourceManager.GetString("nshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string open {
            get {
                return ResourceManager.GetString("open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Park.
        /// </summary>
        public static string park {
            get {
                return ResourceManager.GetString("park", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slave.
        /// </summary>
        public static string slave {
            get {
                return ResourceManager.GetString("slave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slaved.
        /// </summary>
        public static string slaved {
            get {
                return ResourceManager.GetString("slaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slewing.
        /// </summary>
        public static string slewing {
            get {
                return ResourceManager.GetString("slewing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string stop {
            get {
                return ResourceManager.GetString("stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpark.
        /// </summary>
        public static string unpark {
            get {
                return ResourceManager.GetString("unpark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unslave.
        /// </summary>
        public static string unslave {
            get {
                return ResourceManager.GetString("unslave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather.
        /// </summary>
        public static string weather {
            get {
                return ResourceManager.GetString("weather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to west.
        /// </summary>
        public static string west {
            get {
                return ResourceManager.GetString("west", resourceCulture);
            }
        }
    }
}
